import 'package:re_use/types/item.dart';

const List<Item> seededItems = <Item>[
  Item(
    id: '1',
    title: 'Bosch Drill Set',
    description: 'Cordless drill with battery and charger.',
    locationCity: 'Utrecht',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/drill-toolbox/600/400',
    ownerName: 'Mila Verhoeven',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-mila/100/100',
    category: 'Tools',
    typePayment: TypePayment.day,
    price: 8.0,
  ),
  Item(
    id: '2',
    title: 'Camping Tent 2P',
    description: 'Lightweight two-person tent for weekend trips.',
    locationCity: 'Amsterdam',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/camping-tent/600/400',
    ownerName: 'Lars de Jong',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-lars/100/100',
    category: 'Outdoor',
    typePayment: TypePayment.week,
    price: 22.5,
  ),
  Item(
    id: '3',
    title: 'Kitchen Mixer',
    locationCity: 'Rotterdam',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/kitchen-mixer/600/400',
    ownerName: 'Noa Smit',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-noa/100/100',
    category: 'Kitchen',
    typePayment: TypePayment.hour,
    price: 3.0,
  ),
  Item(
    id: '4',
    title: 'Mountain Bike',
    description: 'Trail bike with helmet and lock included.',
    locationCity: 'Eindhoven',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/mountain-bike/600/400',
    ownerName: 'Jesse van Dijk',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-jesse/100/100',
    category: 'Sports',
    typePayment: TypePayment.day,
    price: 15.0,
  ),
  Item(
    id: '5',
    title: 'Projector HD',
    description: 'Portable home cinema projector.',
    locationCity: 'Haarlem',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/projector-hd/600/400',
    ownerName: 'Sophie Kramer',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-sophie/100/100',
    category: 'Electronics',
    typePayment: TypePayment.day,
    price: 12.0,
  ),
  Item(
    id: '6',
    title: 'Electric Pressure Washer',
    description: 'Great for patio and driveway cleaning.',
    locationCity: 'Groningen',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/pressure-washer/600/400',
    ownerName: 'Tom Bakker',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-tom/100/100',
    category: 'Garden',
    typePayment: TypePayment.day,
    price: 10.0,
  ),
  Item(
    id: '7',
    title: 'DJI Mini Drone',
    description: 'Compact drone with spare battery.',
    locationCity: 'Leiden',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/dji-drone/600/400',
    ownerName: 'Ruben Meijer',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-ruben/100/100',
    category: 'Tech',
    typePayment: TypePayment.week,
    price: 35.0,
  ),
  Item(
    id: '8',
    title: 'Sewing Machine',
    description: 'Beginner-friendly model with accessories.',
    locationCity: 'Tilburg',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/sewing-machine/600/400',
    ownerName: 'Eva Jansen',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-eva/100/100',
    category: 'Crafts',
    typePayment: TypePayment.day,
    price: 9.5,
  ),
];
