import 'package:re_use/types/item.dart';

const List<Item> seededItems = <Item>[
  Item(
    id: '1',
    title: 'Bosch Drill Set',
    description: 'Cordless drill with battery and charger.',
    locationCity: 'Antwerpen',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/drill-toolbox/600/400',
    ownerName: 'Mila Verhoeven',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-mila/100/100',
    category: 'Tools',
    typePayment: TypePayment.dag,
    price: 8.0,
    ownerId: 'user1',
    latitude: 51.2213,
    longitude: 4.4051,
  ),
  Item(
    id: '2',
    title: 'Camping Tent 2P',
    description: 'Lightweight two-person tent for weekend trips.',
    locationCity: 'Brussel',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/camping-tent/600/400',
    ownerName: 'Lars de Jong',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-lars/100/100',
    category: 'Outdoor',
    typePayment: TypePayment.week,
    price: 22.5,
    ownerId: 'user2',
    latitude: 50.8503,
    longitude: 4.3517,
  ),
  Item(
    id: '3',
    title: 'Kitchen Mixer',
    locationCity: 'Gent',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/kitchen-mixer/600/400',
    ownerName: 'Noa Smit',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-noa/100/100',
    category: 'Kitchen',
    typePayment: TypePayment.uur,
    price: 3.0,
    ownerId: 'user3',
    latitude: 51.0543,
    longitude: 3.7174,
  ),
  Item(
    id: '4',
    title: 'Mountain Bike',
    description: 'Trail bike with helmet and lock included.',
    locationCity: 'Leuven',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/mountain-bike/600/400',
    ownerName: 'Jesse van Dijk',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-jesse/100/100',
    category: 'Sports',
    typePayment: TypePayment.dag,
    price: 15.0,
    ownerId: 'user4',
    latitude: 50.8798,
    longitude: 4.7005,
  ),
  Item(
    id: '5',
    title: 'Projector HD',
    description: 'Portable home cinema projector.',
    locationCity: 'Berchem',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/projector-hd/600/400',
    ownerName: 'Sophie Kramer',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-sophie/100/100',
    category: 'Electronics',
    typePayment: TypePayment.dag,
    price: 12.0,
    ownerId: 'user5',
    latitude: 51.1989,
    longitude: 4.4329,
  ),
  Item(
    id: '6',
    title: 'Electric Pressure Washer',
    description: 'Great for patio and driveway cleaning.',
    locationCity: 'Mechelen',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/pressure-washer/600/400',
    ownerName: 'Tom Bakker',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-tom/100/100',
    category: 'Garden',
    typePayment: TypePayment.dag,
    price: 10.0,
    ownerId: 'user6',
    latitude: 51.0259,
    longitude: 4.4776,
  ),
  Item(
    id: '7',
    title: 'DJI Mini Drone',
    description: 'Compact drone with spare battery.',
    locationCity: 'Brugge',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/dji-drone/600/400',
    ownerName: 'Ruben Meijer',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-ruben/100/100',
    category: 'Tech',
    typePayment: TypePayment.week,
    price: 35.0,
    ownerId: 'user7',
    latitude: 51.2093,
    longitude: 3.2247,
  ),
  Item(
    id: '8',
    title: 'Sewing Machine',
    description: 'Beginner-friendly model with accessories.',
    locationCity: 'Hasselt',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/sewing-machine/600/400',
    ownerName: 'Eva Jansen',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-eva/100/100',
    category: 'Crafts',
    typePayment: TypePayment.dag,
    price: 9.5,
    ownerId: 'user8',
    latitude: 50.9307,
    longitude: 5.3386,
  ),
  Item(
    id: '9',
    title: 'Yoga Mat & Blocks',
    description: 'Non-slip mat with two foam blocks.',
    locationCity: 'Luik',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/yoga-mat/600/400',
    ownerName: 'Léa Dupont',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-lea/100/100',
    category: 'Sports',
    typePayment: TypePayment.dag,
    price: 5.0,
    ownerId: 'user9',
    latitude: 50.6326,
    longitude: 5.5797,
  ),
  Item(
    id: '10',
    title: 'Electric Scooter',
    description: 'Foldable e-scooter, 25 km range.',
    locationCity: 'Rotterdam',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/electric-scooter/600/400',
    ownerName: 'Daan Visser',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-daan/100/100',
    category: 'Transport',
    typePayment: TypePayment.dag,
    price: 18.0,
    ownerId: 'user10',
    latitude: 51.9225,
    longitude: 4.4792,
  ),
  Item(
    id: '11',
    title: 'Telescopic Ladder 3m',
    description: 'Aluminium ladder, folds compact.',
    locationCity: 'Namen',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/telescopic-ladder/600/400',
    ownerName: 'Marc Lecomte',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-marc/100/100',
    category: 'Tools',
    typePayment: TypePayment.dag,
    price: 7.0,
    ownerId: 'user11',
    latitude: 50.4669,
    longitude: 4.8675,
  ),
  Item(
    id: '12',
    title: 'Stand-up Paddleboard',
    description: 'Inflatable SUP with paddle and pump.',
    locationCity: 'Amsterdam',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/paddleboard/600/400',
    ownerName: 'Fleur de Boer',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-fleur/100/100',
    category: 'Outdoor',
    typePayment: TypePayment.dag,
    price: 25.0,
    ownerId: 'user12',
    latitude: 52.3676,
    longitude: 4.9041,
  ),
  Item(
    id: '13',
    title: 'Karaoke Set',
    description: 'Two wireless mics and speaker included.',
    locationCity: 'Charleroi',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/karaoke-set/600/400',
    ownerName: 'Julie Renard',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-julie/100/100',
    category: 'Electronics',
    typePayment: TypePayment.uur,
    price: 6.0,
    ownerId: 'user13',
    latitude: 50.4108,
    longitude: 4.4444,
  ),
  Item(
    id: '14',
    title: 'Petrol Lawn Mower',
    description: 'Self-propelled mower, 46cm cut width.',
    locationCity: 'Kortrijk',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/lawn-mower/600/400',
    ownerName: 'Pieter Declercq',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-pieter/100/100',
    category: 'Garden',
    typePayment: TypePayment.dag,
    price: 20.0,
    ownerId: 'user14',
    latitude: 50.8282,
    longitude: 3.2648,
  ),
  Item(
    id: '15',
    title: 'DSLR Camera Kit',
    description: 'Canon EOS with 18-55mm and 50mm lens.',
    locationCity: 'Utrecht',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/dslr-camera/600/400',
    ownerName: 'Nina Hendriks',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-nina/100/100',
    category: 'Tech',
    typePayment: TypePayment.dag,
    price: 30.0,
    ownerId: 'user15',
    latitude: 52.0907,
    longitude: 5.1214,
  ),
  Item(
    id: '16',
    title: 'Camping Tent 4P',
    description: 'Spacious family tent with porch.',
    locationCity: 'Eindhoven',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/tent-4p/600/400',
    ownerName: 'Sander Willems',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-sander/100/100',
    category: 'Outdoor',
    typePayment: TypePayment.week,
    price: 28.0,
    ownerId: 'user16',
    latitude: 51.4416,
    longitude: 5.4697,
  ),
  Item(
    id: '17',
    title: 'Acoustic Guitar',
    description: 'Full-size with capo and tuner.',
    locationCity: 'Aalst',
    locationCountry: 'Belgium',
    imageUrl: 'https://picsum.photos/seed/acoustic-guitar/600/400',
    ownerName: 'Amber Goossens',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-amber/100/100',
    category: 'Music',
    typePayment: TypePayment.week,
    price: 14.0,
    ownerId: 'user17',
    latitude: 50.9368,
    longitude: 4.0413,
  ),
  Item(
    id: '18',
    title: 'Pressure Cooker 6L',
    description: 'Stainless steel with safety valve.',
    locationCity: 'Den Haag',
    locationCountry: 'Netherlands',
    imageUrl: 'https://picsum.photos/seed/pressure-cooker/600/400',
    ownerName: 'Bart van der Berg',
    ownerAvatarUrl: 'https://picsum.photos/seed/avatar-bart/100/100',
    category: 'Kitchen',
    typePayment: TypePayment.dag,
    price: 6.0,
    ownerId: 'user18',
    latitude: 52.0705,
    longitude: 4.3007,
  ),
];
