// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE1qW8vDUjDAWMgFZwduGHVwGfqrR9dU8',
    appId: '1:582540204588:web:04a2462c9b076eea46cf89',
    messagingSenderId: '582540204588',
    projectId: 're-use-8d584',
    authDomain: 're-use-8d584.firebaseapp.com',
    storageBucket: 're-use-8d584.firebasestorage.app',
    measurementId: 'G-PJER49FG5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuONmtdvjRZtn_LhTt2ZIBWJc_G4WkVs',
    appId: '1:582540204588:android:af6d3da48d03fdef46cf89',
    messagingSenderId: '582540204588',
    projectId: 're-use-8d584',
    storageBucket: 're-use-8d584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8DR46CAjAJimuHDgRpN8X7RH4p3vLgM',
    appId: '1:582540204588:ios:960cbc0ec83ccd4246cf89',
    messagingSenderId: '582540204588',
    projectId: 're-use-8d584',
    storageBucket: 're-use-8d584.firebasestorage.app',
    iosBundleId: 'com.example.reUse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8DR46CAjAJimuHDgRpN8X7RH4p3vLgM',
    appId: '1:582540204588:ios:960cbc0ec83ccd4246cf89',
    messagingSenderId: '582540204588',
    projectId: 're-use-8d584',
    storageBucket: 're-use-8d584.firebasestorage.app',
    iosBundleId: 'com.example.reUse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE1qW8vDUjDAWMgFZwduGHVwGfqrR9dU8',
    appId: '1:582540204588:web:825c9368f5fc25ec46cf89',
    messagingSenderId: '582540204588',
    projectId: 're-use-8d584',
    authDomain: 're-use-8d584.firebaseapp.com',
    storageBucket: 're-use-8d584.firebasestorage.app',
    measurementId: 'G-0K86F6LTB1',
  );
}
